/usr/lib/ruby/1.8/*/plasma_applet.so
/usr/share/kde4/apps/plasma_scriptengine_ruby/package_ruboid.rb
/usr/share/kde4/apps/plasma_scriptengine_ruby/applet.rb
/usr/share/kde4/apps/plasma_scriptengine_ruby/data_engine.rb
/usr/share/kde4/services/plasma-scriptengine-ruby-package.desktop
/usr/share/kde4/services/plasma-scriptengine-ruby-applet.desktop
/usr/share/kde4/services/plasma-scriptengine-ruby-dataengine.desktop
/usr/lib/ruby/1.8/KDE/plasma.rb
