.TH RBRCC "1" "October 2008" "KDE4 version 4.1" 
.SH NAME
rbkconfig_compiler4 \- KDE config resource compiler

.SH SYNOPSIS
.B rbkconfig_compiler4
[options]
.I inputs
file.kcfg
file.kcfgc

.SH DESCRIPTION

.B rbkconfig_compiler4
compiles KDE config resources into ruby code.

.SH OPTIONS
.TP
.BI -L, --license
Displays software license
.TP
.BI -d, --directory <directory>
Directory to generate files in. By default it is set to the current directory.
.TP
.BI -h, --help
Display option summary

.SH AUTHOR
.B rbrcc
is based on the 
.B rcc 
program from the Qt distribution. 

This manual page was written by David
Palacio for the Debian project, but may be used by others.
Based on Vincent Fourmond work on QtRuby.
